FROM node:8

ENV HOME /{{ name }}

WORKDIR ${HOME}
ADD . $HOME

RUN yarn install

ENV NODE_ENV production

# envs --
ENV SITE_URL https://{{ name }}.firebaseapp.com

ENV FUNC_URL https://us-central1-{{ name }}.cloudfunctions.net
# -- envs

RUN yarn build:app
RUN yarn build:api && cd functions && yarn install
