FROM node:8

ENV HOME /{{ name }}

WORKDIR ${HOME}
ADD . $HOME

RUN yarn install

ENV NODE_ENV production

# envs --
ENV SITE_URL <SITE_URL>
ENV FUNC_URL <FUNC_URL>

ENV SENTRY_DSN <SENTRY_DSN>
# -- envs

RUN yarn build:app
RUN yarn build:api && cd functions && yarn install
